#!/bin/bash

# CSS
cat $(find client -type f -name "*.css" ! -path "*lib*" ! -name "*min*") |
    minify --mime=text/css -o client/min/mithril-keep.min.css;

# JavaScript
cat $(find client -type f -name "*.js" ! -path "*lib*" ! -name "*min*") |
    minify --mime=text/javascript -o client/min/mithril-keep.min.js;
