#!/bin/bash

declare basepwd;
basepwd="$(basename "${PWD}")";

declare -r DIR_TOP="mithril-keep";
declare -r DIR_MID="server";
declare -r DIR_LOW="src";

declare dir="";

case "${basepwd}" in
    "${DIR_TOP}" )
        dir="${DIR_MID}/${DIR_LOW}";
        ;;
    "${DIR_MID}" )
        dir="${DIR_LOW}";
        ;;
    "${DIR_LOW}" )
        dir="";
        ;;
    * )
        echo "Change directory to either '${DIR_TOP} or '${DIR_TOP}/${DIR_MID}'";
        exit 1;
        ;;
esac;

if [ -n "${dir}" ]; then
    pushd "${dir}" &>/dev/null;
fi;

(
    (
        echo "Building Windows binary...";
        GOOS=windows go build &&
            mv -f src.exe ../bin/server.exe;
    ) &&

    (
        echo "Building Mac binary...";
        GOOS=darwin go build &&
            mv -f src ../bin/server_darwin;
    ) &&

    (
        echo "Building Linux binary...";
        GOOS=linux go build &&
            mv -f src ../bin/server_linux;
    )
) &&
    echo "Success!";
